# Generated by Django 5.2 on 2025-04-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_store_product_created_at_product_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
